block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
    "build-riscv (stable%)",
    "build-riscv (1.59.0%)",
    "build-others (%)",
    "clippy (stable%)",
    "rustfmt",
]
