name: Changelog check

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  changelog-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check which component is modified 
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            riscv:
              - 'riscv/**'
            riscv-rt:
              - 'riscv-rt/**'
            riscv-pac:
              - 'riscv-pac/**'

      - name: Check for CHANGELOG.md (riscv)
        if: steps.changes.outputs.riscv == 'true'
        uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: ./riscv/CHANGELOG.md
          skipLabels: 'skip changelog'
          missingUpdateErrorMessage: 'Please add a changelog entry in the riscv/CHANGELOG.md file.'

      - name: Check for CHANGELOG.md (riscv-rt)
        if: steps.changes.outputs.riscv-rt == 'true'
        uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: ./riscv-rt/CHANGELOG.md
          skipLabels: 'skip changelog'
          missingUpdateErrorMessage: 'Please add a changelog entry in the riscv-rt/CHANGELOG.md file.'
      
      - name: Check for CHANGELOG.md (riscv-pac)
        if: steps.changes.outputs.riscv-pac == 'true'
        uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: ./riscv-pac/CHANGELOG.md
          skipLabels: 'skip changelog'
          missingUpdateErrorMessage: 'Please add a changelog entry in the riscv-pac/CHANGELOG.md file.'
