name: Clippy

on:
  push:
    branches: [ staging, trying, master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

env:
  CLIPPY_PARAMS: -W clippy::all -W clippy::pedantic -W clippy::nursery -W clippy::cargo

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cargo_flags:
          - "--no-default-features"
          - "--all-features"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: Run clippy
        run: cargo clippy --all ${{ matrix.cargo_flags }} -- -D warnings
